services:
  hive-db:
    image: postgres:13
    container_name:   hive-db
    hostname:   hive-db
    environment:
      POSTGRES_DB: 'metastore_db'
      POSTGRES_USER: 'hive'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5433:5432'

  metastore:
    image: apache/hive:3.1.3
    container_name: metastore
    hostname: metastore
    environment:
      HIVE_METASTORE_DB_TYPE: postgres
      HIVE_METASTORE_URI: thrift://metastore:9083
      HADOOP_CLASSPATH: /opt/hadoop/jars/*
      DB_DRIVER: postgres
      SERVICE_NAME: 'metastore'
      SERVICE_OPTS: '-Xmx1G -Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver
                      -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://hive-db:5432/metastore_db
                      -Djavax.jdo.option.ConnectionUserName=hive
                      -Djavax.jdo.option.ConnectionPassword=password'
    ports:
        - '9083:9083'
    volumes:
      - ./hive/conf/hive-site.xml:/opt/hive/conf/hive-site.xml
      - ./spark/jars:/opt/hadoop/jars
    depends_on:
      - hive-db
