services:
    minio:
        ports:
            - 9000:9000
            - 9001:9001
        environment:
            MINIO_ROOT_USER: minioadmin
            MINIO_ROOT_PASSWORD: minioadmin
        volumes:
            - ./docker-volumes/minio/data:/data
        image: minio/minio:RELEASE.2025-04-22T22-12-26Z-cpuv1
        command: server /data --console-address ":9001"

    createbuckets:
        image: minio/mc
        depends_on:
            - minio
        entrypoint: >
            /bin/sh -c "
            sleep 5;
            /usr/bin/mc config host add minioinstance http://minio:9000 minioadmin minioadmin;
            /usr/bin/mc rm -r --force minioinstance/${RAW_BUCKET_NAME};
            /usr/bin/mc mb minioinstance/${RAW_BUCKET_NAME};
            /usr/bin/mc policy download minioinstance/${RAW_BUCKET_NAME};
            /usr/bin/mc rm -r --force minioinstance/${WAREHOUSE_BUCKET_NAME};
            /usr/bin/mc mb minioinstance/${WAREHOUSE_BUCKET_NAME};
            /usr/bin/mc policy download minioinstance/${WAREHOUSE_BUCKET_NAME};
            exit 0;
            "