# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

x-common-config: &common-config
  environment: &common-env
    MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
    MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    MINIO_ENDPOINT_URL: ${MINIO_ENDPOINT_URL}
    WAREHOUSE_BUCKET_NAME: ${WAREHOUSE_BUCKET_NAME}
    RAW_BUCKET_NAME: ${RAW_BUCKET_NAME}
    
    SPARK_MODE: master
    SPARK_RPC_AUTHENTICATION_ENABLED: no
    SPARK_RPC_ENCRYPTION_ENABLED: no
    SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: no
    SPARK_SSL_ENABLED: no
    SPARK_USER: spark
  volumes: &common-volumes
    - ./src:/src

services:
  spark-master:
    <<: *common-config
    build:
      context: .
      dockerfile: spark.Dockerfile
    ports:
      - 8088:8080

  spark-worker:
    <<: *common-config
    build:
      context: .
      dockerfile: spark.Dockerfile
    environment:
      <<: *common-env
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_MEMORY: 1G
      SPARK_WORKER_CORES: 1

  jupyter:
    depends_on:
      - spark-master
    build:
      context: .
      dockerfile: spark.Dockerfile
    command: python -m jupyterlab --ip "0.0.0.0" --no-browser --NotebookApp.token=''
    ports:
      - 8888:8888
    volumes:
      - ./jupyter:/app
      - ./src:/src
    working_dir: /app
    environment:
      <<: *common-env
      JUPYTER_ENABLE_LAB: yes
      PYTHONPATH: /:/opt/bitnami/spark/python/

